### PR TITLE
Accepts all kinds of Array-like objects

### PR DESCRIPTION
**Pull request by bfred-it**
This should now be supported:

```js
balanceText(document.body.children); // HTMLCollection
balanceText(jQuery('.balanceme')); // Array-like
```

and previously-supported `NodeList`s and selectors should be slightly faster because I'm skipping the `Array.prototype.slice` call for all.

Replaces/includes #95 and #96

### CODE REVIEW

**Comment by bfred-it** [comment]
I'm gonna make a few more small changes

**Comment by BrianGenisio** [comment]
Lots of good cleanups in here.  I think there is room for a lot more, but to avoid too much of a diff, I think they are warranted in a separate PR.

I'm curious what bugs you were running in to regarding array-likes.  I had tested jQuery lists and node lists by hand.  I'm glad you codified it, though, in the `interface.htm` file.

Thanks for these clean-ups :)

**Comment by bfred-it** [comment]
In that "bugs" commit, respectively:

- typo
- `[el,el].concat(nodelist)` is `[el,el,nodelist]` rather than `[el,el,el,el]`, so concat needs to be applied
- `elements` at that point might also be a single element

**Comment by redmunds** [comment]
This Looks good to me. I tested on Mac10.10/Chrome, Mac10.10/Safari, Win10/Firefox, and Win10/Edge.

@bfred-it @BrianGenisio Any last changes you want to get in before I merge?

**Comment by BrianGenisio** [comment]
LGTM!!!!

**Comment by redmunds** [comment]
@BrianGenisio @bfred-it @Rycochet Thanks for your contributions. This is awesome!

**Comment by bfred-it** [comment]
Excellent! I'll publish to npm this weekend. Remind me if I forget 😂

**Comment by bfred-it** [comment]
v3 published

Thanks a lot for this, @BrianGenisio!

**Comment by BrianGenisio** [comment]
Thanks @bfred-it!!!!  So exciting!!!  I just published the [`react-balance-text`](https://github.com/Khan/react-balance-text) component using it and it will be going into prod on our site next week. 

Also, thanks to @redmunds for this very helpful utility AND for being patient with me on this re-write :)

**Pull request merged**
