### PR TITLE
Fix issue where non-breaking-space is included as a break character.

### PR DESCRIPTION
**Pull request by bjnsn**
This makes the definition of a 'break-opportunity' consistent with browsers' existing line-breaking algorithms.

Side note: The [contribution agreement](http://adobe-webplatform.github.com/balance-text/cla/balancetext-cla.html) page isn't confirming authorizations as expected, so I'm unsure whether that has been received on your end.

### CODE REVIEW

**Comment by redmunds** [comment]
@bjnsn Thanks for PR! Also, thanks for head's up about contribution agreement page -- I'll need to straighten that out first and then review your code.

**Comment by redmunds** [comment]
@bjnsn Sorry for the delay. The [CLA page](
http://adobe-webplatform.github.com/balance-text/cla/balancetext-cla.html) should be fixed. Can you try again?

**Comment by bjnsn** [comment]
That worked - I've signed off.

**Comment by redmunds** [comment]
Looks good. Thanks.

**Pull request merged**
