### PR TITLE
Only add selector if it exists

### PR DESCRIPTION
**Pull request by bfred-it**

### CODE REVIEW

**Comment by redmunds** [comment]
@bfred-it Thank you for your contribution. You'll need to agree to the CLA before it can be accepted.

Also, can you provide a simple example of how you're hitting this case?

**Comment by bfred-it** [comment]
```js
$('.selector').first().balanceText();
```

**Comment by redmunds** [comment]
@bfred-it Thanks for reporting this problem. This does not fix the problem in the case that I tried. I edited test/test1.html and changed `$(".custom-class").balanceText()` to be `$(".custom-class").first().balanceText()` and opened the page in Chrome on Mac 10.10. var `selector` was ".custom-class.slice(0,1)" so checking for this change did not prevent the problem.

Which browser & OS does this fix it on?

I think this can probably be fixed using a regex to detect case where selector has parens (i.e. is a function call) and skipping those cases. What do you think?

cc @rileyjshaw

**Comment by rileyjshaw** [comment]
Oh, wow! I hadn't tested for this case, thanks for catching this.

[According to the docs](https://api.jquery.com/selector/), it looks like `.selector` isn't what we're looking for. The docs' proposed solution (passing in the selector string as an argument), however, makes for a pretty messy API.

We _could_ just go ahead with `.selector` and do some simple pattern matching as suggested, but there's no guarantee that it'll be supported in the future. Thoughts?

**Comment by bfred-it** [comment]
`jQuery.fn` methods are meant to operate on the current selection, so I would suggest to use the current selection instead of their selector.

`$elements.balanceText(skipResize)` should only operate on the selected elements. Automatically trying to match the selector seems too _magical_ to me, especially in these cases.

If you want to provide an interface to link balanceText to a selector, use something like this:

```js
$.balanceText('selector');
```

**Comment by rileyjshaw** [comment]
:+1: :+1: big fan of that

**Comment by bfred-it** [comment]
Implemented in a different PR 🙂

**Pull request closed without merging**
